cc_test (
    name = "configuration_test",
    srcs = [
        "Configuration_test.cpp",
    ],
    deps = [
        "@com_google_googletest//:gtest",
        "@com_google_googletest//:gtest_main",
        "//lib/config:config_lib",
        "@com_github_google_glog//:glog",
    ],
)