cc_test (
    name = "engine_test",
    srcs = [
        "Comparator_test.cpp",
    ],
    deps = [
        "@com_google_googletest//:gtest",
        "@com_google_googletest//:gtest_main",
        "//lib/engine:engine_lib",
    ],
    linkstatic = 1,
)