cc_test (
    name = "message_test",
    srcs = [
        "Message_test.cpp",
    ],
    deps = [
        "@com_google_googletest//:gtest",
        "@com_google_googletest//:gtest_main",
         "//message:message",
    ],
)